### PR TITLE
feat(frontend): return page is now available

### PR DESCRIPTION
**Pull request by Loste1k**

### CODE REVIEW

**Comment by lightumcc** [comment]
Function test is passed, found one backend issue.😉

**Comment by iewnfod** [comment]
Can you add a function bar on the top? You can view how to implement it through my recent commits.

**Comment by lightumcc** [comment]
Applying BREAKING CHANGE to the backend, please wait for my upstream commits

**Review by lightumcc — APPROVED** [review]
Due to complex branch problem, I'll approve this pr and then modify on main

**Pull request merged**
